name: Keep Supabase Alive

on:
  schedule:
    # Run at midnight (0 0 * *) on Sunday (0) and Friday(5)
    - cron: '0 0 * * 0,5'
  workflow_dispatch:

jobs:
  test-insert-delete:
    runs-on: ubuntu-latest

    steps:
      - name: Insert a test row into Supabase
        id: insert
        run: |
          RESPONSE=$(curl -s -X POST "${{ secrets.SUPABASE_URL }}/rest/v1/Recettes" \
            -H "apikey: ${{ secrets.SUPABASE_KEY }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_KEY }}" \
            -H "Content-Type: application/json" \
            -H "Prefer: return=representation" \
            --data '{"title":"test_github_actions", "category":"plat", "vegan":"FALSE"}'

          echo "API RESPONSE: $RESPONSE"

          # Extraction de l'id depuis le JSON retourné
          ID=$(echo "$RESPONSE" | jq -r '.[0].id')

          echo "INSERTED_ID=$ID" >> $GITHUB_OUTPUT

      - name: Delete the previously created row
        run: |
          curl -X DELETE "${{ secrets.SUPABASE_URL }}/rest/v1/Recettes?id=eq.${{ steps.insert.outputs.INSERTED_ID }}" \
            -H "apikey: ${{ secrets.SUPABASE_KEY }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_KEY }}"
